# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3418c9aab697919f1b65663ca61948e73e6d5e1e1e3af87dba1809c028ca1c25e5b324c151f2996a5066e192dd840c4b4114ecacea0fe422e6432801f1a3199d

test:
  secret_key_base: eb249145193bff1c86a6df1b967b6a2d45e4acfad3d47bd7a6dc5ab48faf98c6bf3dd203c84036df3df98c5cdf5b6db5491541a5483201dd41842accb0df9cbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
